# Generated by Django 5.1.7 on 2025-04-06 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('prerequisites', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course_order', models.JSONField()),
                ('enroll_time', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.concept')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course')),
            ],
        ),
        migrations.CreateModel(
            name='PrerequisiteDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_relations', to='recommender.concept')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_relations', to='recommender.concept')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
        ),
    ]
