# Generated by Django 5.1.6 on 2025-03-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='学校ID')),
                ('name', models.CharField(max_length=200, verbose_name='学校名称')),
                ('about', models.TextField(blank=True, verbose_name='学校简介')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校列表',
            },
        ),
    ]
