# Generated by Django 5.1.7 on 2025-04-05 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_concept_courseconcept_prerequisitedependency_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseconcept',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='关系ID'),
        ),
        migrations.AlterField(
            model_name='prerequisitedependency',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='前置关系ID'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='用户课程关系ID'),
        ),
    ]
